// Generated by https://quicktype.io

export interface Encuesta {
    CodigoEncuesta: number;
    R1:             string;
    R2:             string;
    R3:             string;
    R4:             string;
    NombreUsuario:  string;
}
