// Generated by https://quicktype.io

export interface Numjugadas {
    Codigojugadas:            number;
    JugadasImagenFantasia:    number;
    JugadasImagenTerror:      number;
    JugadasPreguntasFantasia: number;
    JugadasPreguntasTerror:   number;
    JugadasMusicaFantasia:    number;
    JugadasMusicaTerror:      number;
}
