// Generated by https://quicktype.io

export interface Ranking {
    CodigoRanking:           number;
    PuntosImagenFantasia:    number;
    PuntosImagenTerror:      number;
    PuntosPreguntasFantasia: number;
    PuntosPreguntasTerror:   number;
    PuntosMusicaFantasia:    number;
    PuntosMusicaTerror:      number;
    nombre:                  string;
}
